### ISSUE TITLE
Not So Much a Bug But an Undesired Feature

### ISSUE THREAD

**Issue by FastEddie49** [nebhead/PiFire#144]
My system is the dual system that I can run either the PiFire or the OEM controller. My system is based on a RPi Model B+ v1.2. Because of the duality, I am using the 4-relay board, and I noticed that during bootup, two of the relays were chattering for a short period, turning off and on rapidly. Once the PiFire software took control, the relays returned to normal (off, active high). The outputs involved were AUG and FAN, and a little bit of digging turned up that those two GPIO pins (GPIO 14 and 15) are used by default by the RPi serial port and apparently there is some activity there during bootup. It was a simple matter to disable the serial port through Raspi-config and that took care of the issue.

Also, the GPIO 4 (TxD/Transmit) that controls the IGN relay --  the status LED on the relay board is dimly lit during bootup but again drops out when PiFire takes control, even after disabling the serial port. There is some sort of leakage there but it's not enough to trigger the relay so I didn't worry about it.

Thinking about this further, it might be that GPIO 4 is configured by default with a pullup rather than a pulldown...

**Comment by nebhead** [comment]
Hey @FastEddie49 - Yes, this is definitely a design flaw that I wish I had anticipated before building out the PCBs.  That said, the design does 'gate' power to the functional relays.  GPIO4 is the Power Gate relay, which shouldn't fully activate, and allow the other relays to energize during boot time.  All that said, in future PCB designs, it might be wise to move those GPIOs to ones that aren't being utilized by the RPi during boot up.  

Also, I think it's probably also wise to include disabling of the serial port during installation, so that users don't need to consider this in the future.  I'll assign this issue to myself and look into making the installer script changes.

**Comment by nebhead** [comment]
Planned fix in v1.8.0 with the release of v4.0.1 PCB with different GPIOs for the relay controls.
